version: "4.3"

services:

# DATABASE
  # mysql-database:
  #   image: mysql/mysql-server:8.0.32
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #   ports:
  #     - target: 3306
  #       published: 3306
  #       protocol: tcp
  #   restart: always  


# FASTAPI

  data-fastapi:
    build:
      context: ./data-fastapi
    # Assurez-vous que le nom de l'image correspond au service
    image: protojam-data-fastapi
    volumes:
      - ./data:/data-fastapi/app/
    tty: true
    ports:
      # Vous pouvez utiliser la notation courte pour mapper les ports
      - "8000:8000"  # Port local : Port dans le conteneur
      
# STREAMLIT
  data-streamlit:
    build:
      context: ./data-streamlit
    # depends_on:
    #   mysql-database:
    #     condition: service_healthy
    volumes:
      - ./data:/app/streamlit
    tty: true
    ports:
      # HTTP
      - target: 8501
        published: 8501
        protocol: tcp